
# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.

# Project information
site_name: WSO2 API Platform for Kubernetes Documentation 1.0.0
site_description: Documentation for WSO2 API Platform for Kubernetes
site_author: WSO2
site_url: https://apk.docs.wso2.com/en/latest/

# Repository
repo_name: wso2/docs-apk
repo_url: https://github.com/wso2/docs-apk
edit_uri: https://github.com/wso2/docs-apk/edit/1.0.0/en/docs/
dev_addr: localhost:8000

# Copyright
copyright: WSO2 API Platform for Kubernetes - Documentation

# Configuration
theme:
    name: material
    custom_dir: theme/material
    palette:
        primary: deep-orange
        accent: deep-orange
    logo: images/logo.svg
    favicon: images/favicon.png
    highlightjs: true
    feature:
        tabs: true
    language: 'en'
#Breaks build if there's a warning
strict: false
# Navigation
nav:
    - Documentation: index.md
    - Get Started:
        - Quick Start Guide: get-started/quick-start-guide.md
        - Concepts:
            - Architecture: get-started/architecture.md
            - Gateway: get-started/gateway.md
        - About this Release: get-started/about-this-release.md
    - Develop and Deploy API:
        - Create an API from a Service:
            - Create an API: develop-and-deploy-api/api-from-a-service/create-an-api.md
            - Attach an interface to the API: develop-and-deploy-api/api-from-a-service/attach-api-interface.md
        - Discover Your Services: develop-and-deploy-api/discover-your-services.md
        - Create an API Proxy:
            - From Scratch: develop-and-deploy-api/create-an-api-proxy/from-scratch.md
            - From an Existing Definition: 
                - REST API from an OAS: develop-and-deploy-api/create-an-api-proxy/from-existing-definition/rest-api-using-oas.md
        - Test API: develop-and-deploy-api/test-api.md
        - CI/CD: develop-and-deploy-api/ci-cd.md
        - GraphQL: 
            - Test API: develop-and-deploy-api/test-graphql-api.md
        - WebSocket:
            - Test API: develop-and-deploy-api/test-websocket-api.md
        - SOAP:
            - Test API: develop-and-deploy-api/test-soap-api.md
        - API Versions:
            - Create an API Version: develop-and-deploy-api/api-versions/create-an-api-versions.md
            - Default Version: develop-and-deploy-api/api-versions/default-version.md
            - Backward Compatibility: develop-and-deploy-api/api-versions/backward-compatibility.md
        - API Policies:
            - Overview: develop-and-deploy-api/api-policies-overview.md
            - Attach Policies: develop-and-deploy-api/api-policies/attach-policies.md
            - Create a Policy: develop-and-deploy-api/api-policies/create-a-policy.md
        - Rate Limiting: develop-and-deploy-api/rate-limiting.md
        - API Security:
            - Authentication:
                - Enable API Security:
                    - JWT: develop-and-deploy-api/security/authentication/enable-api-security/jwt.md
                    - MTLS: develop-and-deploy-api/security/authentication/enable-api-security/mtls.md
                    - API Key: develop-and-deploy-api/security/authentication/enable-api-security/api-key.md
                    - Internal Key: develop-and-deploy-api/security/authentication/enable-api-security/internal-key.md
                - Disable API Security: develop-and-deploy-api/security/authentication/disable-api-security.md
            - Authorization:
                - Access Control for API Requests: develop-and-deploy-api/security/authorization/access-control-for-api-requests.md
    - Manage APIs:
        - API Documentation: manage-apis/api-documentation.md
        - Consumer Management:
            - Subscription Availability: manage-apis/consumer-management/subscription-availability.md
            - API Visibility: manage-apis/consumer-management/api-visibility.md
        - Usage Plans:
            - Add a New Rate Limiting Policy: manage-apis/usage-plans/add-a-new-rate-limiting-policy.md
            - Set Limits for Rate Limiting: manage-apis/usage-plans/set-limits-for-rate-limiting.md
        - Lifecycle Management:
            - API Lifecycle Overview: manage-apis/lifecycle-management/api-lifecycle-overview.md
            - Manage API Lifecycle: manage-apis/lifecycle-management/manage-api-lifecycle.md
            - Customize API Lifecycles: manage-apis/lifecycle-management/customize-api-lifecycles.md
            - Extending API Lifecycles: manage-apis/lifecycle-management/extending-api-lifecycles.md
        - Community Engagement:
            - Community URLs: manage-apis/community-engagement/community-urls.md
            - Share API Link: manage-apis/community-engagement/comment-on-api.md
            - Comment on API: manage-apis/community-engagement/comment-on-api.md
        - API Categorization: manage-apis/api-categorization.md
        - API Monetization: manage-apis/api-monetization.md
        - Publish Your API: manage-apis/publish-your-api.md

# Extensions
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
          linenums: true
          use_pygments: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
          permalink: true
    - markdown_include.include:
          base_path: docs
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.snippets:
          base_path: docs
    - attr_list
plugins:
    - search
    - markdownextradata: {}
    - exclude:
          glob:
              - wip/*
    #- redirects:
    #      redirect_maps:

    # Extra
extra_css:
    - assets/lib/highlightjs/default.min.css
    - assets/css/theme.css
    - assets/lib/json-formatter/json-formatter.css
extra_javascript:
    - assets/lib/json-formatter/json-formatter.umd.js
    - assets/lib/highlightjs/highlight.min.js
    - assets/js/theme.js
    - assets/lib/backtotop/js/util.js
    - assets/lib/backtotop/js/main.js
extra:
    social:
        - type: github
          link: https://github.com/wso2
        - type: twitter
          link: https://twitter.com/wso2
        - type: linkedin
          link: https://www.linkedin.com/company/wso2
    site_version: 1.0.0
    base_path: http://localhost:8000
    #base_path: https://apk.docs.wso2.com/en/1.0.0
    envoy_path: https://www.envoyproxy.io/docs/envoy/v1.20.0
